---
version: '3'
services:
  Elmo:
      image: freqtradeorg/freqtrade:develop
      restart: unless-stopped
      container_name: Elmo
      volumes:
        - "./user_data:/freqtrade/user_data"
      ports:
        - "0.0.0.0:8030:8080"
      command: >
        trade
        --dry-run
        --dry-run-wallet 1000
        --db-url sqlite:////freqtrade/user_data/db/dev-Elmo.sqlite
        --logfile /freqtrade/user_data/logs/Elmo.log
        --config /freqtrade/user_data/configs/binance/Elmo-pair.json
        --config /freqtrade/user_data/configs/Elmo.json
        --config /freqtrade/user_data/configs/spot-market.json
        --config /freqtrade/user_data/configs/instances/Elmo.json
        --strategy Elmo

